<?php

namespace ContainerAmJjs5D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UqO1m4YService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uqO1m4Y' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uqO1m4Y'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'generator' => ['privates', '.errored..bhYiIj', NULL, 'Cannot determine controller argument for "App\\Controller\\logController::index()": the $generator argument is type-hinted with the non-existent class or interface: "App\\Controller\\GreetingGenerator". Did you forget to add a use statement?'],
            'logger' => ['privates', 'monolog.logger', 'getMonolog_LoggerService', true],
        ], [
            'generator' => '?',
            'logger' => '?',
        ]);
    }
}
