<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXiq5wnv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXiq5wnv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXiq5wnv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXiq5wnv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXiq5wnv\App_KernelDevDebugContainer([
    'container.build_hash' => 'Xiq5wnv',
    'container.build_id' => 'dfafbd8a',
    'container.build_time' => 1605097464,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXiq5wnv');
