<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQX1H3NA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQX1H3NA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQX1H3NA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQX1H3NA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQX1H3NA\App_KernelDevDebugContainer([
    'container.build_hash' => 'QX1H3NA',
    'container.build_id' => '4633fc68',
    'container.build_time' => 1604508873,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQX1H3NA');
